### ISSUE TITLE
AOT compilation fails with "unresolved external symbol __svml_log2_ha"

### ISSUE THREAD

**Issue by hnra** [numba/numba#5670]
I'm trying to do AOT compilation for a Python module but keep running into the follow or similar errors:

```
error LNK2001: unresolved external symbol __svml_log2_ha
fatal error LNK1120: 1 unresolved externals
```

I also get similar errors but with log4, exp2, and exp4 in my project. There seems to be something missing in my build environment such that the SVML functions can't be found. I have tried changing cpu_target, adding intel and numba channels to conda, installing Parallel Studio from Intel etc.

Here's a minimal reproducible example:

```python
import setuptools

import numpy as np
from numba.pycc import CC

cc = CC("min_ex")

@cc.export("foo", "f8[:]()")
def foo():
    z = np.ones(10_000_000)
    return np.log(z)

setuptools.setup(
    name="min-example", packages=setuptools.find_packages(), ext_modules=[cc.distutils_extension()]
)
```

My `meta.yml` file is as follow:

```
package:
  name: min-example
  version: "0.1"

source:
  path: .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python>=3.7
    - setuptools
    - numpy>=1.14.6
    - scipy
    - numba==0.49

  run:
    - python
```

System Information:
Window 10
Anaconda (fresh install)
Intel® Xeon® Processor E3-1245 v5 
VS Build Tools installed
